import os
from typing import Optional

from .models import GeneratedFile, GeneratedFileListResponse


class GeneratedFileManager:
    """Manage files generated by background tasks (exports, workflows, etc.).

    REST API:
        GET    /api/generated-files
        GET    /api/generated-files/:id/download
        DELETE /api/generated-files/:id
    """

    def __init__(self, client):
        self.client = client
        self.base_url = "/generated-files"

    def list(
        self,
        page: int = 1,
        page_size: int = 10,
        search_query: Optional[str] = None,
        order_by: str = "createdAt",
        order_direction: str = "desc",
    ) -> GeneratedFileListResponse:
        """List generated files for the current user."""
        params = {
            "page": page,
            "pageSize": page_size,
            "orderBy": order_by,
            "orderDirection": order_direction,
        }
        if search_query:
            params["searchQuery"] = search_query.strip()

        response_data = self.client.get(self.base_url, params=params)
        return GeneratedFileListResponse(**response_data)

    def download(
        self,
        file_id: int,
        local_path: str,
        chunk_size: int = 8192,
    ) -> str:
        """Download a generated file by ID to a local path or directory."""
        url = f"{self.client.base_url}{self.base_url}/{file_id}/download"
        response = self.client.session.get(url, stream=True)
        if not response.ok:
            from .exceptions import GeopackAPIError

            raise GeopackAPIError.from_response(response)

        content_disposition = response.headers.get("Content-Disposition")
        filename = None
        if content_disposition and "filename=" in content_disposition:
            filename = content_disposition.split("filename=")[1].strip('"')

        if not filename:
            filename = f"generated_file_{file_id}"

        if os.path.isdir(local_path):
            target_file = os.path.join(local_path, filename)
        else:
            target_file = local_path

        with open(target_file, "wb") as f:
            for chunk in response.iter_content(chunk_size=chunk_size):
                f.write(chunk)

        return os.path.abspath(target_file)

    def delete(self, file_id: int) -> None:
        """Delete a generated file record and its storage (204 No Content)."""
        self.client.delete(f"{self.base_url}/{file_id}")
